[package]
name = "ascii_art_rs"
version = "0.5.0"
edition = "2021"

[lib]
name = "ascii_art_rs"
crate-type = [ "cdylib",]

[dependencies]
numpy = "0.21"

[dependencies.pyo3]
version = "0.21"
features = [ "extension-module",]
