[package]
name = "ascii_art_rs"
version = "0.5.0"
edition = "2021"

[lib]
name = "ascii_art_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
